module Sprockets
  autoload :ArgumentError,       "sprockets/errors"
  autoload :ConcatenatedAsset,   "sprockets/concatenated_asset"
  autoload :ContentTypeMismatch, "sprockets/errors"
  autoload :Context,             "sprockets/context"
  autoload :DirectiveParser,     "sprockets/directive_parser"
  autoload :Environment,         "sprockets/environment"
  autoload :Error,               "sprockets/errors"
  autoload :FileNotFound,        "sprockets/errors"
  autoload :Pathname,            "sprockets/pathname"
  autoload :Processor,           "sprockets/processor"
  autoload :Server,              "sprockets/server"
  autoload :SourceFile,          "sprockets/source_file"
  autoload :StaticAsset,         "sprockets/static_asset"
end
